openSUSE/news-o-o

- _includes/header.html
Let search box shrink a bit, instead of wrap menu items.
> fix responsive navbar

- _posts/2020-04-15-Jitsi-Instance-on-meet-opensuse-org.md
All people with an openSUSE community account are allowed.
> Not only openSUSE Members are allowed.

- _posts/2020-05-20-Cloud-based-workers-for-openQA.md
Fix typos, grammar and spelling and minor corrections to the phrasing.
> Fix and improve 2020-05-20-Cloud-based-workers-for-openQA.md

- Gemfile.lock
- _config.yml
> update to theme 0.5.0

- Gemfile.lock
Need to update to version 0.6.0 to apply the fix of social icons
> Update to jekyll-theme 0.6.0

- README.md
The bundle command can't be found via zypper se bundle, so describing how to find it.
> added needed packages for bundle

- index.html
This is a HTML validation error.
> Add missing alt for <img>

- _posts/2021-12-23-bar-holidays.md
@knurpht asked me to post this, so here it is.
I know this is a bit late, but I still hope we can get this merged before Christmas ;)
The idea is to have an event where people who can't celebrate Christmas/New Year like they normally would can hang out in the bar.
Happy holidays!
~ Jens
> Add a post about holiday events in the bar

- _posts/2022-07-01-osa-cfp.md
Hi Doug,
We extend CFP deadline.
Please accept this.
Thanks.
> extend deadline and correct schedule

- _posts/2023-01-23-new-4096-bit-signing-key.md
the switchover is plannaed to happen tomorrow jan 23rd
> add a post about the new 4096 bit signing key

- _posts/2023-01-24-opensuse-simplifies-codec-install.md
force accept I think it's bit misleading
> Remove the screenshot of snippet. It's bit misleading

- _posts/2023-02-06-novo-forum-em-portugues.md
> fix post title for new openSUSE forum in portugues

- _posts/2023-02-06-novo-forum-em-portugues.md
"a longo termo" does not sound good, it should be "a longo prazo"
> Fix wording

- _posts/2023-04-27-leap-micro-54-leap-155-enters-rc.md
Read to go live, unless you see some issues
> Update the 5.4 GA announcement plus leap 155 rc

- _posts/2022-11-08-os-site-aligns-w-upstream-documentation.md
related with this, I also sent a PR to universe.o.o repo to add manpages to that resource.
Greetings.
> fix manpage index url

- _posts/2023-10-12-leap-micro-55-hands-on.md
> Leap Micro 5.5 GA annoucement and 5.3 EOL

- _posts/2023-11-19-opensuse-asia-summit-2024-call-for-host.md
added two mails in mailto field, hope it works properly...
> add mailto tag in asia summit article

- _posts/2024-03-29-xz-backdoor.md
This wasn't the issue
This reverts commit beb2fbf2990669df3652875275326c7c956da89d.
> Revert "updating post icon"

- _posts/2024/2024-05-23-openSUSE-Asia-2024-CFL.md
We start openSUSE Asia Summit 2024 call for logo with this announcement.
Thanks
> add openSUSE Asia Summit 2024 CFL

- _posts/2024/2024-06-12-new-NVIDIA-signing-key.md
preannounce new NVIDIA signing key
> add new nvidia signing key

- _posts/2024/2024-06-19-os-leap-micro-reaches-beta.md
> Leap Micro 6.0 Beta

- Gemfile.lock
- _posts/2024/2024-06-21-leap-15.6-image-respin.md
> Leap 15.6 image respin

- Gemfile.lock
revert gemfile to the state with Micro 6.0 Beta article
> Revert gemfile.lock

- _posts/2024/2024-06-25-opensuse-asia-summit-2025-call-for-host.md
We want to publish openSUSE.Asia Summit Call For Host 2025. Thank you.
> create openSUSE.Asia Summit Call For Host 2025

- _layouts/post.html
Use toot.kytta.dev for share. More info on https://github.com/andypiper/mastodon-embeds-examples
> toot tool for share

- _posts/2024/2024-09-20-quickstart-fde-yast2.md
openSUSE MicroOS should be of course openSUSE Tumbleweed
> Fix distribution name

- _posts/2023/2023-03-28-leapmicro-54-beta-hands-on.md
This seemed to be the only article using it.
> Use Leap Micro tag instead of LeapMicro for 54 hands on

- _posts/2024/2024-10-07-leap-16-0-prealpha.md
Initial feedback was questioning ALP.
> Add ALP reference

- _posts/2024/2024-09-20-quickstart-fde-yast2.md
Hi,
Was following this blog post and found a small typo on the package name so thought of correcting it.
Many thanks !
Lucas
> Correct tpm2.0-tools package name in FDE blog post.

- _posts/2024/2024-11-26-transition-from-windows-step-by-step.md
Colons make for mapping values, the title must be a string.
> Repair YAML in 2024-11-26

- _posts/2024/2024-11-29-try-opensuse-migration-tool-leap-micro-61-beta.md
- _posts/2024/2024-12-04-leap-micro-61-rc.md
* Simple RC annoucement
* Fixes to 6.1 Beta article
> Leap Micro 6.1 RC article

- assets/css/app.css
#273 
I solve this dark theme should not be white and i change color
> Code block on dark theme should not be white

- _posts/2025/2025-01-16-gaming-on-linux-how-os-stacks-up.md
> fix markdown style

- _posts/2025/2025-02-12-os-licensing-gets-ai-upgrade.md
See https://www.llama.com/llama3/license/
> SUSE and openSUSE do not own the LLama trademark, remove references

- _posts/2025/2025-02-20-setup-fde-on-opensuse.md
> Fix some typos in 2025-02-20 blog

- _posts/2025/2025-04-01-tw-monthly-update-march.md
> fix the keywords

- _posts/2025/2025-07-12-local-llm-with-openSUSE.md
> update and change publishing time

- _posts/2025/2025-08-26-building-edge-ai-infrastructure-with-opensuse.md
Hi @ddemaio , 
Raising a PR for the Building Edge AI Infrastructure with KVM, openSUSE, and Ollama guide as openSUSE News post. Please let me know if you've got any feedback on this. 
Thanks! 
cc: @bwgartner, @tlssuse, @andavissuse
> docs: add building-edge-ai-infra with opensSUSE post

- _posts/2025/2025-09-03-leap-16-doubles-support.md
> Add 24 months of Leap support article
